spring.application.name=gestor_tareas


spring.datasource.url=jdbc:h2:mem:gestion_tareas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=HolaSoyUnKeyParaUnaPruebaTecnica


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


logging.level.org.hibernate.SQL=debug

